aerogearcatalog/metrics-apb

roles/provision-prometheus-apb/defaults/main.yml

After *successful* provision of grafana it starts miss-configured. 
All files are in right directories, but it seems that master image comes with broken json format. 
It also seems that json format is not stable and dashboards will probably will need to be reconfigured after 4.7.0 release which may be created soon. Using latest image resolves the problem with missing dashboards. Users will still need to replicate datasource . 
Current images.
```
master 4 days ago
latest  25 days ago
```
See: https://hub.docker.com/r/grafana/grafana/tags/

Update grafana image to latest

---

roles/provision-metrics-apb/tasks/main.yml

Just a tiny thing I missed in https://github.com/aerogearcatalog/metrics-apb/pull/7
This is necessary to allow scaling of the Grafana pods

fix: create a ReadWriteMany PVC for Grafana

---

roles/provision-metrics-apb/tasks/main.yml

If the deploymentconfig is created before the serviceaccount it can result in a warning in the events tab. 
```service account myproject/oauth-proxy was not found```
Creating the serviceaccount before the deploymentconfig should eliminate this warning.

Create oauth-proxy serviceaccount before deploymentconfig

---

roles/provision-metrics-apb/defaults/main.yml

The prometheus image we are using in the metrics-apb should be the official productised Red Hat image. 
This PR changes the image in the apb to the latest official image.

use latest productised image

---

roles/provision-metrics-apb/tasks/main.yml

Wait until all container become ready before exiting the APB provision pod. Uses a jsonpath expression to get the ready status of all containers in all pods. 
To verify, build and push this branch and provision the APB to a project. Don't close the Window, but wait until it turns green. After that go to the project overview: all pods should be up and running (blue).

AEROGEAR-1796 wait for containers to become ready

---

roles/provision-metrics-apb/tasks/main.yml

Add the 'grafana-internal` service that exposes grafana to internal HTTP requests in order to allow access to the `/metrics` endpoint to Prometheus without authentication.
Related to https://github.com/aerogear/service-docs/pull/4

Add grafana-internal service to allow access from prometheus

---

Jenkinsfile

@grdryn based on your suggestion from previous PR
I was also discussing with @AdamSaleh that maybe we could add the name of the branch to the project name, but this would be quite risky, because OpenShift project names may only contain lower-case letters, numbers, and dashes. So we would need another function to check that.
wdyt

More unique name for the OpenShift project name

---

roles/deprovision-metrics-apb/tasks/main.yml
roles/provision-metrics-apb/defaults/main.yml
roles/provision-metrics-apb/files/grafana-dashboards-provider.yml
roles/provision-metrics-apb/files/grafana-fh-sync-dashboard.json
roles/provision-metrics-apb/files/grafana-primary-dashboard.json
roles/provision-metrics-apb/tasks/main.yml
roles/provision-metrics-apb/templates/grafana-config-map.ini.j2

This PR implements Grafana Auto Dashboard Discovery. The description of how this works comes straight from the [metrics proposal](https://github.com/aerogear/proposals/blob/master/metrics/prometheus-metrics-endpoints-and-auto-discovery.md#metrics-service):
The 5.x stream of Grafana has the ability to load dashboards from disk and update the dashboards when the files on disk are also updated. This is possible using something called a provider. A provider is a configuration item that tells Grafana how and where to load dashboards. The idea is in the future Grafana may have different providers for loading dashboards from disk, source control, via an API, etc.
In the grafana `.ini` file, a provisioning path is configured:
```ini
provisioning = /etc/grafana/conf/provisioning
```
The …

Grafana Auto Dashboards

---

roles/provision-metrics-apb/defaults/main.yml
roles/provision-metrics-apb/files/grafana-dashboards-provider.yml
roles/provision-metrics-apb/tasks/main.yml

Myself and @StevenTobin have built a custom Grafana image based off the Grafana master branch at a certain point in time. The image also has the [pie chart panel](https://grafana.com/plugins/grafana-piechart-panel) and [worldmap panel](https://grafana.com/plugins/grafana-worldmap-panel) plugins baked in baked in by default.
It's been pushed to https://hub.docker.com/r/aerogearcatalog/grafana/. This PR switches us over to using that image. (also minor side note: it also enables debug logging in Grafana by default)
* We're using features that are only available on the master branch of Grafana. These features will become GA with the Grafana 5.0 release in the next few months. Right now the problem is the master branch is pretty unstable. We've run into a couple of issues where dashboard and …

use aerogearcatalog custom Grafana image

---

README.md
roles/provision-metrics-apb/files/mobile-services-dashboard.json
roles/provision-metrics-apb/tasks/main.yml

JIRA: https://issues.jboss.org/browse/AEROGEAR-1963
This is a dashboard that will be available when deploying **metrics**. It will display a couple of metrics from each service and whether or not these services are provisioned, simply as a summary. The main dashboard of each service will be added separately when it's provisioned. For instance a project with Keycloak and Push would have the following dashboards in Grafana:
- Mobile Services
- Keycloak
- Push
The following images represent the current state of the work. The main idea is that each service will be contained in a row that is collapsable.
This way the user can choose in an orderly fashion what to see.
Once provisioned, a service would be displayed like:

Adds mobile services dashboard

---

Jenkinsfile
roles/test-provision-apb/tasks/main.yml

This PR adds some checks in the current test-provision role. It makes sure the following config maps are present:
- grafana-dashboards-configmap
- grafana-dashboards-providers-configmap
- grafana-datasources-configmap
- grafana-ini-configmap
- prometheus-configmap
And the following secret:
- prometheus_secret

Adds test checks for config-maps and secret

---

roles/test-provision-apb/tasks/main.yml

Fixes this kind of warning:
```
[logs:pod/testing-pod] TASK [test-provision-apb : Get Grafana dashboards configmap] *******************
[logs:pod/testing-pod]  [WARNING]: when statements should not include jinja2 templating delimiters
[logs:pod/testing-pod] such as {{ }} or {% %}. Found: "{{ grafana_dashboards_configmap_name }}" not in
[logs:pod/testing-pod] grafana_dashboards_configmap.stdout
```
Reference: https://github.com/ansible/ansible/issues/22397

Fixed jinja2 warnings

---

roles/provision-metrics-apb/files/mobile-services-dashboard.json

Update mobile services dashboard for mobile app metrics.
Screenshot:
Notes:
* Because of https://issues.jboss.org/browse/AEROGEAR-2199, no "Version" and "Provisioned" boxes unlike Keycloak and Sync rows.
* No links to detail dashboards. Detail dashboards: graphs that filter data based on app id, platform etc. similar to <https://snapshot.raintank.io/dashboard/snapshot/onsMFzn5t2uAZBB7NhGJAAVYFaeA9Jxq?orgId=2> but with more filters.
Data in the screenshot is generated using https://github.com/aliok/aerogear-mobile-metrics-api-data-generator

AEROGEAR-2046 Update mobile services dashboard for mobile app metrics

---

roles/deprovision-metrics-apb/tasks/main.yml
roles/provision-metrics-apb/tasks/provision-app-metrics.yml
roles/provision-metrics-apb/templates/configmap.yml.j2
roles/test-deprovision-apb/tasks/main.yml

This PR adds the config map to the metrics apb that is required to get the client config via the mobile-cli. It also changes the URL of the app metrics service to https and adds some additional tests.
To verify:
1. Deploy the APB
2. Provision a Client App to the same namespace, e.g. https://github.com/aerogearcatalog/android-app-apb
3. Retrieve the configuration via `mobile get clientconfig <app name> --namespace=<project> -o json`. Ths config should contain a section for metrics. The only config value is the URL.

integrate metrics service with mobile cli

---

apb.yml
roles/provision-metrics-apb/defaults/main.yml

https://issues.jboss.org/browse/AEROGEAR-2351
1. Clone this branch, build & push this APB
2. Provision **without** specifying `Postgres User` & `Postgres Password`
* provisioning pod should finish without error
3. Provision **with** specifying `Postgres User` & `Postgres Password`
* after it's provisioned, check aerogear-app-metrics & postgres-metrics DC environment variables - it should contain your values in `POSTGRESQL_USER` & `POSTGRESQL_PASSWORD` variables

Pass config variables correctly

---

roles/provision-metrics-apb/defaults/main.yml

It never made sense to have this image in the aerogearcatalog Dockerhub org. However, we didn't have permissions at the time.
Now that I have access, I've pushed it to the right org.

fix: use aerogear/grafana docker image

---

Makefile

Don't force the use of the containerised apb tools in Makefile commands, apb should be installed locally using one of the recommended approaches https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/apb_cli.md#installing-the-apb-tool

AEROGEAR-2491 - Don't force the use of the containerised apb tools in Makefile command.

---

roles/provision-metrics-apb/files/mobile-services-dashboard.json

https://issues.jboss.org/browse/AEROGEAR-3134
This change is for clientId count on the 'Mobile security metrics' panel on the 'Mobile Services' dashboard.
The client count on the main 'Mobile security metrics' dashboard is already using 'count(DISTINCT clientId)'.

🐛 AEROGEAR-3134 Use DISTINCT when aggregating unique clients for security check metrics

---

Jenkinsfile

Tests are now performed on internal infrastructure.

Test on ci-rhos ocp slave

---

apb.yml

Update docs links. The docs for all platforms are contained in a single document (with tabbed boxes with instructions per platform). Thats why they all point to the same URL.

update docs links

---

roles/provision-metrics-apb/templates/prometheus-config-map.yml.j2

How to verify:
- Provision this PR of the APB
- Clone the test app `https://github.com/aliok/node-app-with-prometheus-metrics.git`
- Switch to project running the metrics apb: `oc project foo`
- Deploy the test app: `oc new-app -f openshift-template.json`
- This will deploy the test app with **annotations on the service**.
- Delete the annotation `org.aerogear.metrics/plain_endpoint: /metrics` from the test app service
- Add the same annotation to the test app pod
- Check the pod logs: you should see requests coming at `/metrics`
- Scale the test app up (need to add the annotation to new pods manually) and make sure you see log entries as above

Configure Prometheus to auto discover pods as scraping targets

---

Dockerfile
roles/provision-metrics-apb/files/mobile-services-dashboard.json

https://issues.jboss.org/browse/AEROGEAR-7651
* addressed warning from provisioning pod: `DEPRECATED: APB playbooks should be stored at /opt/apb/project`
* few changes to graphs in Mobile Services Dashboard related to Sync
* This APB was temporarily provisioned here (should be available during review time of this PR): https://grafana-metrics.apb-testing.skunkhenry.com/dashboard/db/mobile-services?orgId=1 - check that out

Additional changes to Mobile Services Dashboard (sync)

---

Dockerfile

* previous change resolved the problem with warning about deprecation of playbooks location, see https://github.com/aerogearcatalog/metrics-apb/commit/5039e2865bbe9572970965db99724c463518706b
* local push and provision did work, also apb test passed successfully, however after the new image was build and pushed to dockerhub repo, it's not possible to provision the APB anymore (log from provision pod: `'provision' NOT IMPLEMENTED`)

Reverting the change of playbooks' location

---

roles/provision-metrics-apb/files/mobile-services-dashboard.json

https://issues.jboss.org/browse/AEROGEAR-8528
* fixed panel for detection of Keycloak service in the namespace
* replaced `Version` panel with `Current memory`, see screenshot

fix: fixes to keycloak panels

---

roles/oc-patch-file-to-configmap/Readme.md
roles/oc-patch-file-to-configmap/tasks/main.yml
roles/oc-patch-file-to-configmap/templates/oc-patch.json.j2
roles/provision-metrics-apb/defaults/main.yml
roles/provision-metrics-apb/tasks/provision-grafana.yml

https://issues.jboss.org/browse/AEROGEAR-8317
1. Spin up minishift and/or configure ASB on your cluster with `psturc` organisation and tag `AEROGEAR-8317`
1. Provision keycloak-apb
1. Provision metrics-apb
1. Verify `keycloak-dashboard.json` is present in `grafana-dashboards-configmap`
1. Go to Grafana and expand list of dashboards - `Keycloak metrics` dashboard should be present

Add keycloak-dashboard.json to Grafana dashboards if it's present in a project

---

roles/provision-metrics-apb/defaults/main.yml
roles/provision-metrics-apb/tasks/add-dashboards-to-grafana.yml
roles/provision-metrics-apb/tasks/provision-grafana.yml

https://issues.jboss.org/browse/AEROGEAR-8512
1. Spin up minishift and/or configure ASB on your cluster with `psturc` organisation and tag `AEROGEAR-8512`
1. Provision keycloak-apb
1. Provision sync-app-apb with params:
* docker image: `docker.io/psturc/voyager-server-example-metrics`
* metrics endpoint: `metrics`
* sync app port: `4000`
* rest of params doesn't matter
1. Provision metrics-apb
1. Verify `keycloak-dashboard.json` and `sync-app-<your-app-name>-dashboard.json` are present in `grafana-dashboards-configmap`
1. Go to Grafana and expand list of dashboards - `IDM metrics` and Sync app dashboards should be present

feat: add supported dashboards from ns to grafana

---

roles/unbind-metrics-apb/tasks/main.yml

https://issues.jboss.org/browse/AEROGEAR-8214
I can't really reproduce the problem because I think it only happens when bind is somehow failed.
However, we can prevent the unbind action from crashing by check conditions and also handling the errors.

fix: do not crash if there are errors during unbind

---

roles/provision-metrics-apb/files/mobile-services-dashboard.json

This is deploy here: https://master.uxreview-bcc8.openshiftworkshop.com/console/project/test-kc-customised/overview.
If you check the dashboard, keycloak has no memory usage, and if you check Prometheus, you will see there are metrics about UPS memory usage.

fix: add missing tag for keycloak memory metrics query
